// ── App reducer ──────────────────────────────────────────────────────────────
// One reducer for all domain state. Randomness and ids are generated by the
// caller and passed in on the action, so the reducer stays pure (StrictMode
// may call it twice).

import { ASSETS, DAY_MS, FEE_AED, SPARKLINE_POINTS, type AssetId } from '../config';
import { COPY } from '../copy';
import { findOrder, log, move, notify, notifyCancelledBatch, notifyPlaced, reconcileSellCap, roundPrice, sweepExpiry, todayPrice, type Ctx } from '../engine/ledger';
import { customerBuyPrice, stepMid } from '../engine/priceEngine';
import { runPollTick } from '../engine/triggerEngine';
import { validateTicket } from '../engine/validation';
import type { MarketTrade, Order, PaymentMethod, Side, TicketDraft } from '../types';
import { initialState, type AppState } from './state';

export interface InjectSpec {
  id: string;
  asset: AssetId;
  side: Side;
  /** Your price relative to today's customer price, e.g. -0.005 = 0.5% below. */
  offset: number;
  amountAed?: number;
  grams?: number;
  validityDays: number;
  paymentMethod?: PaymentMethod;
  createdAgoMs?: number;
}

export type Action =
  | { type: 'PRICE_TICK'; shocks: Record<AssetId, number>; realNow: number }
  | { type: 'POLL_TICK'; rands: number[]; realNow: number }
  | { type: 'PLACE_ORDER'; orderId: string; draft: TicketDraft; realNow: number }
  | { type: 'CARD_AUTH_RESULT'; orderId: string; realNow: number }
  | { type: 'CANCEL_ORDER'; orderId: string; reason: 'user' | 'change'; realNow: number }
  | { type: 'MARKET_SELL'; tradeId: string; asset: AssetId; grams: number; realNow: number }
  | { type: 'MARKET_BUY'; tradeId: string; asset: AssetId; amountAed: number; method: PaymentMethod; realNow: number }
  | { type: 'MARK_ALL_READ' }
  // Demo panel
  | { type: 'DEMO_SET_BUY_PRICE'; asset: AssetId; buy: number; realNow: number }
  | { type: 'DEMO_NUDGE'; asset: AssetId; pct: number; realNow: number }
  | { type: 'DEMO_TOGGLE_PAUSE'; asset: AssetId; paused?: boolean; realNow: number }
  | { type: 'DEMO_SET_POLL'; ms: number }
  | { type: 'DEMO_SET_BUFFER'; asset: AssetId; buffer: number; realNow: number }
  | { type: 'DEMO_SET_JITTER'; jitter: number }
  | { type: 'DEMO_SET_JITTER_ADVERSE'; adverse: boolean; realNow: number }
  | { type: 'DEMO_FAST_FORWARD'; ms: number; label: string; realNow: number }
  | { type: 'DEMO_SET_WALLET'; aed: number; realNow: number }
  | { type: 'DEMO_SET_HOLDINGS'; asset: AssetId; grams: number; realNow: number }
  | { type: 'DEMO_FORCE_AUTH_FAIL'; on: boolean; realNow: number }
  | { type: 'DEMO_FORCE_DEBIT_DECLINE'; on: boolean; realNow: number }
  | { type: 'DEMO_INJECT_ORDERS'; specs: InjectSpec[]; realNow: number }
  | { type: 'DEMO_HINT'; hint: string | null }
  | { type: 'DEMO_LOG'; msg: string; realNow: number }
  | { type: 'RESET'; realNow: number };

/** Clone state into a mutable draft and build a context for ledger helpers. */
function begin(state: AppState, realNow: number): Ctx {
  return { s: structuredClone(state), now: realNow + state.clockOffsetMs, realNow };
}

function pushHistory(s: AppState, asset: AssetId): void {
  const m = s.market[asset];
  m.history = [...m.history.slice(-(SPARKLINE_POINTS - 1)), customerBuyPrice(asset, m.mid)];
}

function createOrder(ctx: Ctx, id: string, d: TicketDraft, createdAt: number): Order {
  const s = ctx.s;
  const order: Order = {
    id,
    seq: s.nextSeq++,
    asset: d.asset,
    side: d.side,
    limitPrice: d.limitPrice,
    amountAed: d.side === 'buy' ? d.amountAed : undefined,
    grams: d.side === 'sell' ? d.grams : undefined,
    paymentMethod: d.side === 'buy' ? d.paymentMethod ?? 'wallet' : undefined,
    validityDays: d.validityDays,
    createdAt,
    expiresAt: createdAt + d.validityDays * DAY_MS,
    status: 'DRAFT',
    timeline: [{ status: 'DRAFT', at: createdAt, note: COPY.timeline.placed }],
    expiryWarned: false,
  };
  s.orders.push(order);
  log(ctx, 'transition', `${id}: created DRAFT · ${d.side} ${d.asset} @ ${d.limitPrice} · ${d.side === 'buy' ? `AED ${d.amountAed} via ${order.paymentMethod}` : `${d.grams} g`} · ${d.validityDays}d`);
  return order;
}

export function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case 'PRICE_TICK': {
      const market = { ...state.market };
      for (const asset of Object.keys(market) as AssetId[]) {
        const m = market[asset];
        if (m.paused) continue;
        const mid = stepMid(asset, m.mid, action.shocks[asset]);
        market[asset] = {
          ...m,
          mid,
          history: [...m.history.slice(-(SPARKLINE_POINTS - 1)), customerBuyPrice(asset, mid)],
        };
      }
      return { ...state, market };
    }

    case 'POLL_TICK': {
      const ctx = begin(state, action.realNow);
      let i = 0;
      const rand = () => action.rands[i++ % action.rands.length];
      runPollTick(ctx, rand);
      ctx.s.lastPollRealAt = action.realNow;
      return ctx.s;
    }

    case 'PLACE_ORDER': {
      const ctx = begin(state, action.realNow);
      const d = action.draft;
      const v = validateTicket(ctx.s, {
        asset: d.asset,
        side: d.side,
        limitPrice: d.limitPrice,
        amountAed: d.amountAed ?? NaN,
        grams: d.grams ?? NaN,
        replaceSellOrders: d.replaceSellOrders,
      });
      if (!v.ok) {
        log(ctx, 'demo', `Placement rejected: ${v.priceError ?? v.amountError ?? v.gramsError}`);
        return ctx.s;
      }
      // "Cancel them and sell all": the other sell orders go only now, on placement.
      if (d.side === 'sell' && d.replaceSellOrders) {
        const others = ctx.s.orders.filter(o => o.asset === d.asset && o.side === 'sell' && o.status === 'OPEN');
        for (const o of others) {
          const note = COPY.timeline.replacedBy(action.orderId);
          move(ctx, o.id, 'CANCELLED', note, { cancelReason: note });
        }
        notifyCancelledBatch(ctx, d.asset, others.map(o => o.id), 'replace');
      }
      const order = createOrder(ctx, action.orderId, d, ctx.now);
      if (order.side === 'buy' && order.paymentMethod === 'card') {
        move(ctx, order.id, 'AUTH_PENDING', COPY.timeline.authPending);
      } else {
        const opened = move(ctx, order.id, 'OPEN', COPY.timeline.open);
        notifyPlaced(ctx, opened);
      }
      return ctx.s;
    }

    case 'CARD_AUTH_RESULT': {
      const ctx = begin(state, action.realNow);
      const o = findOrder(ctx.s, action.orderId);
      if (!o || o.status !== 'AUTH_PENDING') return state;
      if (ctx.s.settings.forceCardAuthFail) {
        ctx.s.settings.forceCardAuthFail = false;
        log(ctx, 'demo', 'Forced card authorisation failure consumed');
        move(ctx, o.id, 'AUTH_FAILED', COPY.timeline.authFailed);
      } else {
        log(ctx, 'transition', `${o.id}: AED 0.10 card check approved and refunded`);
        const opened = move(ctx, o.id, 'OPEN', COPY.timeline.authOk);
        notifyPlaced(ctx, opened);
      }
      return ctx.s;
    }

    case 'CANCEL_ORDER': {
      const ctx = begin(state, action.realNow);
      const o = findOrder(ctx.s, action.orderId);
      if (!o || o.status !== 'OPEN') return state;
      const note = action.reason === 'change' ? COPY.timeline.changed : COPY.timeline.cancelled;
      move(ctx, o.id, 'CANCELLED', note, { cancelReason: note });
      return ctx.s;
    }

    case 'MARKET_SELL': {
      const ctx = begin(state, action.realNow);
      const { s } = ctx;
      const price = roundPrice(action.asset, todayPrice(s, action.asset, 'sell'));
      const g = Math.min(action.grams, s.holdings[action.asset]);
      const gross = g * price;
      s.holdings[action.asset] = Math.max(s.holdings[action.asset] - g, 0);
      s.wallet += gross - FEE_AED;
      log(ctx, 'trade', `Manual sell ${g.toFixed(4)} g ${action.asset} @ ${price} · holdings now ${s.holdings[action.asset].toFixed(4)} g`);
      const cancelled = reconcileSellCap(ctx, action.asset);
      const trade: MarketTrade = {
        id: action.tradeId, at: ctx.now, asset: action.asset, side: 'sell', grams: g, price,
        amountAed: gross, fee: FEE_AED, ok: true, cancelledOrderIds: cancelled,
      };
      s.trades.unshift(trade);
      notify(ctx, {
        kind: 'market',
        title: COPY.notif.marketSellTitle(action.asset),
        body: COPY.notif.marketBody(g, gross - FEE_AED, 'sell'),
        asset: action.asset,
        cta: { type: 'view_portfolio', label: COPY.notif.ctaPortfolio },
      });
      return s;
    }

    case 'MARKET_BUY': {
      const ctx = begin(state, action.realNow);
      const { s } = ctx;
      const price = roundPrice(action.asset, todayPrice(s, action.asset, 'buy'));
      const total = action.amountAed + FEE_AED;
      const g = action.amountAed / price;
      const base = {
        id: action.tradeId, at: ctx.now, asset: action.asset, side: 'buy' as const, grams: g, price,
        amountAed: action.amountAed, fee: FEE_AED, method: action.method, cancelledOrderIds: [],
      };
      if (action.method === 'card' && s.settings.forceCardDebitDecline) {
        s.settings.forceCardDebitDecline = false;
        log(ctx, 'fail', 'Manual buy: forced card decline consumed');
        s.trades.unshift({ ...base, ok: false, failReason: 'card_declined' });
        return s;
      }
      if (action.method === 'wallet' && s.wallet + 1e-9 < total) {
        log(ctx, 'fail', `Manual buy: wallet ${s.wallet.toFixed(2)} < ${total.toFixed(2)}`);
        s.trades.unshift({ ...base, ok: false, failReason: 'insufficient_balance' });
        return s;
      }
      if (action.method === 'wallet') s.wallet -= total;
      s.holdings[action.asset] += g;
      s.trades.unshift({ ...base, ok: true });
      log(ctx, 'trade', `Manual buy ${g.toFixed(4)} g ${action.asset} @ ${price} via ${action.method}`);
      notify(ctx, {
        kind: 'market',
        title: COPY.notif.marketBuyTitle(action.asset),
        body: COPY.notif.marketBody(g, total, 'buy'),
        asset: action.asset,
        cta: { type: 'view_portfolio', label: COPY.notif.ctaPortfolio },
      });
      return s;
    }

    case 'MARK_ALL_READ':
      if (state.notifications.every(n => n.read)) return state;
      return { ...state, notifications: state.notifications.map(n => ({ ...n, read: true })) };

    // ── Demo panel ────────────────────────────────────────────────────────────
    case 'DEMO_SET_BUY_PRICE': {
      const ctx = begin(state, action.realNow);
      ctx.s.market[action.asset].mid = action.buy / (1 + ASSETS[action.asset].markup);
      pushHistory(ctx.s, action.asset);
      log(ctx, 'price', `${action.asset} buy price set to ${action.buy}`);
      return ctx.s;
    }

    case 'DEMO_NUDGE': {
      const ctx = begin(state, action.realNow);
      ctx.s.market[action.asset].mid *= 1 + action.pct;
      pushHistory(ctx.s, action.asset);
      const buy = customerBuyPrice(action.asset, ctx.s.market[action.asset].mid);
      log(ctx, 'price', `${action.asset} ${action.pct > 0 ? '+' : ''}${(action.pct * 100).toFixed(1)}% → buy ${buy.toFixed(ASSETS[action.asset].priceDecimals)} / sell ${todayPrice(ctx.s, action.asset, 'sell').toFixed(ASSETS[action.asset].priceDecimals)}`);
      return ctx.s;
    }

    case 'DEMO_TOGGLE_PAUSE': {
      const ctx = begin(state, action.realNow);
      const m = ctx.s.market[action.asset];
      m.paused = action.paused ?? !m.paused;
      log(ctx, 'demo', `${action.asset} price movement ${m.paused ? 'paused' : 'resumed'}`);
      return ctx.s;
    }

    case 'DEMO_SET_POLL':
      return { ...state, settings: { ...state.settings, pollIntervalMs: action.ms } };

    case 'DEMO_SET_BUFFER': {
      const ctx = begin(state, action.realNow);
      ctx.s.settings.buffer[action.asset] = action.buffer;
      log(ctx, 'demo', `${action.asset} buffer set to ${(action.buffer * 100).toFixed(2)}%`);
      return ctx.s;
    }

    case 'DEMO_SET_JITTER':
      return { ...state, settings: { ...state.settings, execJitter: action.jitter } };

    case 'DEMO_SET_JITTER_ADVERSE': {
      const ctx = begin(state, action.realNow);
      ctx.s.settings.jitterAdverse = action.adverse;
      log(ctx, 'demo', `Jitter direction: ${action.adverse ? 'always against user' : 'random'}`);
      return ctx.s;
    }

    case 'DEMO_FAST_FORWARD': {
      const shifted = { ...state, clockOffsetMs: state.clockOffsetMs + action.ms };
      const ctx = begin(shifted, action.realNow);
      log(ctx, 'demo', `Fast-forward ${action.label}`);
      sweepExpiry(ctx);
      return ctx.s;
    }

    case 'DEMO_SET_WALLET': {
      const ctx = begin(state, action.realNow);
      ctx.s.wallet = action.aed;
      log(ctx, 'demo', `Wallet set to AED ${action.aed.toFixed(2)}`);
      return ctx.s;
    }

    case 'DEMO_SET_HOLDINGS': {
      const ctx = begin(state, action.realNow);
      const before = ctx.s.holdings[action.asset];
      ctx.s.holdings[action.asset] = action.grams;
      log(ctx, 'demo', `${action.asset} holdings set ${before.toFixed(4)} → ${action.grams.toFixed(4)} g`);
      if (action.grams < before) reconcileSellCap(ctx, action.asset);
      return ctx.s;
    }

    case 'DEMO_FORCE_AUTH_FAIL': {
      const ctx = begin(state, action.realNow);
      ctx.s.settings.forceCardAuthFail = action.on;
      log(ctx, 'demo', `Force next card save to fail: ${action.on ? 'ON' : 'off'}`);
      return ctx.s;
    }

    case 'DEMO_FORCE_DEBIT_DECLINE': {
      const ctx = begin(state, action.realNow);
      ctx.s.settings.forceCardDebitDecline = action.on;
      log(ctx, 'demo', `Force next card payment to decline: ${action.on ? 'ON' : 'off'}`);
      return ctx.s;
    }

    case 'DEMO_INJECT_ORDERS': {
      const ctx = begin(state, action.realNow);
      for (const spec of action.specs) {
        const today = todayPrice(ctx.s, spec.asset, spec.side);
        const limitPrice = roundPrice(spec.asset, today * (1 + spec.offset));
        const createdAt = ctx.now - (spec.createdAgoMs ?? 0);
        const o = createOrder(ctx, spec.id, { ...spec, limitPrice }, createdAt);
        const savedNow = ctx.now;
        ctx.now = createdAt; // timeline reflects when the order was "placed"
        if (o.paymentMethod === 'card') {
          move(ctx, o.id, 'AUTH_PENDING', COPY.timeline.authPending);
          move(ctx, o.id, 'OPEN', COPY.timeline.authOk);
        } else {
          move(ctx, o.id, 'OPEN', COPY.timeline.open);
        }
        ctx.now = savedNow;
      }
      return ctx.s;
    }

    case 'DEMO_HINT':
      return { ...state, demoHint: action.hint };

    case 'DEMO_LOG': {
      const ctx = begin(state, action.realNow);
      log(ctx, 'demo', action.msg);
      return ctx.s;
    }

    case 'RESET':
      return initialState(action.realNow);
  }
}
